### ISSUE TITLE
Not enough direct memory.

### ISSUE THREAD

**Issue by nmarasoiu** [druid-io/docker-druid#12]
The only modification is to supervisor.conf:
  -Ddruid.processing.numThreads=1
  -Ddruid.processing.buffer.sizeBytes=23000

This was supposed to eliminate the memory issue, but gave this:

2015-10-05T14:00:16,552 WARN [main] io.druid.guice.LifecycleScope - Caught exception when trying to create a[Key[type=io.druid.indexing.worker.executor.ExecutorLifecycle, annotation=[none]]]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:325) ~[druid-services-master-selfcontained.jar:master]
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartHandler(Lifecycle.java:230) ~[druid-services-master-selfcontained.jar:master]
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartManagedInstance(Lifecycle.java:176) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.guice.LifecycleScope$1.get(LifecycleScope.java:76) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1001) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1040) [druid-services-master-selfcontained.jar:master]
        at io.druid.cli.CliPeon.run(CliPeon.java:225) [druid-services-master-selfcontained.jar:master]
        at io.druid.cli.Main.main(Main.java:91) [druid-services-master-selfcontained.jar:master]
Caused by: com.metamx.common.ISE: Failed to run isReady
        at io.druid.indexing.worker.executor.ExecutorLifecycle.start(ExecutorLifecycle.java:124) ~[druid-services-master-selfcontained.jar:master]
        ... 15 more
Caused by: com.metamx.common.ISE: Unable to grant lock to inactive Task [index_wikipedia_2015-10-05T14:00:10.733Z]
        at io.druid.indexing.overlord.TaskLockbox.tryLock(TaskLockbox.java:224) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.overlord.TaskLockbox.tryLock(TaskLockbox.java:201) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.actions.LockTryAcquireAction.perform(LockTryAcquireAction.java:58) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.actions.LockTryAcquireAction.perform(LockTryAcquireAction.java:29) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.actions.LocalTaskActionClient.submit(LocalTaskActionClient.java:62) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.task.AbstractFixedIntervalTask.isReady(AbstractFixedIntervalTask.java:89) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.worker.executor.ExecutorLifecycle.start(ExecutorLifecycle.java:120) ~[druid-services-master-selfcontained.jar:master]
        ... 15 more
2015-10-05T14:00:16,559 ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
java.lang.NullPointerException
        at io.druid.cli.CliPeon.run(CliPeon.java:225) [druid-services-master-selfcontained.jar:master]
        at io.druid.cli.Main.main(Main.java:91) [druid-services-master-selfcontained.jar:master]

**Comment by Fokko** [comment]
Because your machine has more cores, it will require more direct memory, this is fixed by #29.
