### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by dzer6** [druid-io/docker-druid#13]
Steps to reproduce:
1. git clone https://github.com/druid-io/docker-druid.git
2. docker build -t druid/cluster docker-druid

Error message:
```
Oct 28, 2015 8:44:59 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.3.Final
2015-10-28T08:45:00,153 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, directory='druid_extensions', hadoopDependenciesDir='hadoop_druid_dependencies', loadList=null}]
2015-10-28T08:45:01,402 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.metrics.DruidMonitorSchedulerConfig] from props[druid.monitoring.] as [io.druid.server.metrics.DruidMonitorSchedulerConfig@2ca47471]
2015-10-28T08:45:01,408 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.metrics.MonitorsConfig] from props[druid.monitoring.] as [MonitorsConfig{monitors=[]}]
Exception in thread "main" com.google.inject.ProvisionException: Guice provision errors:

1) Unknown provider[mysql] of Key[type=io.druid.metadata.MetadataStorageConnector, annotation=[none]], known options[[derby]]
  at io.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:86)
  while locating io.druid.metadata.MetadataStorageConnector

1 error
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1014)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1040)
	at io.druid.cli.CreateTables.run(CreateTables.java:108)
	at io.druid.cli.Main.main(Main.java:91)
The command '/bin/sh -c /etc/init.d/mysql start && java -cp /usr/local/druid/lib/druid-services-*-selfcontained.jar -Ddruid.extensions.coordinates=[\"io.druid.extensions:mysql-metadata-storage\"] -Ddruid.metadata.storage.type=mysql io.druid.cli.Main tools metadata-init --connectURI="jdbc:mysql://localhost:3306/druid" --user=druid --password=diurd && /etc/init.d/mysql stop' returned a non-zero code: 1
```

**Comment by xvrl** [comment]
Hi @dzer6 I think this might be due to the fact that the extensions loading mechanism has changed in the current master branch, so we will probably have to make some adjustments. Can you try the 0.8.2 branch to see if it works with the current release candidate?

**Comment by dzer6** [comment]
Hi Xavier!

It works for 0.8.2 and 0.8.1 branches but fails for master.

Best Regards,
Andrew

**Comment by xvrl** [comment]
Thanks that's good to know. @guobingkun would you mind having a look at this, and see what tweaks need to be done to get the image to work after merging #1638 ? Ideally if we could make minimal adjustments, this would be a good real-work test to see if pull-deps works as expected to create a deployable directory structure.

**Comment by guobingkun** [comment]
@xvrl Sure, I will take a look at this.

**Comment by guobingkun** [comment]
@dzer6 Thanks for reporting the issue! Do you mind trying https://github.com/druid-io/docker-druid/pull/14 out?

**Comment by dzer6** [comment]
@guobingkun Sure, will try this soon.

**Comment by dzer6** [comment]
@guobingkun checked, works for me, thanks!

**Comment by guobingkun** [comment]
@dzer6 Awesome! Thank you!
